### ISSUE TITLE
Using ponymix with dunst

### ISSUE THREAD

**Issue by simao** [falconindy/ponymix#39]
Hi,

When using ponymix with `notify-osd` it properly shows the volume in a progress bar.

When using `dunst` it just shows a notification with the text `ponymix`. Is there a way to make ponymix generate a notification with the current volume?

Thanks

**Comment by falconindy** [comment]
Sounds like a bug/problem to be solved in dunst (is it even compliant with the FDO notifications spec?)... The notification ponymix emits includes a suggested icon some key/value pairs with the new volume value and a synchronization hint.

**Comment by simao** [comment]
Ok, I guess I'll go back to `notify-osd`, just like `dunst` simplicity
and the damn `notify-osd` notifications don't disappear on mouse over.

Thanks for ponymix it works great.


On Thu, Jun 4, 2015, at 18:37, Dave Reisner wrote:
> Sounds like a bug/problem to be solved in dunst (is it even compliant
> with the FDO notifications spec?)... The notification ponymix emits
> includes a suggested icon some key/value pairs with the new volume
> value and a synchronization hint.


> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/falconindy/ponymix/issues/39#issuecomment-108960860
