### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by rrooij** [falconindy/ponymix#40]
Ponymix has no license currently. This prevents it from being included in the repositories of FSF endorsed distributions. What about using GPLv3 for this piece of software?

**Comment by falconindy** [comment]
Sorry, GPLv3 doesn't jive with me. I'd sooner license this under MIT, which is what I use for the rest of my projects.

**Comment by rrooij** [comment]
The license itself doesn't really matter to me. It's your project. But choosing a license at least can prevent confusion.

**Comment by Earnestly** [comment]
@falconindy Would you mind adding a `LICENSE` file to the repo so that it may be installed?
