### ISSUE TITLE
"is-muted" doesn't work 

### ISSUE THREAD

**Issue by zeni99ArchLinux** [falconindy/ponymix#49]
Hi! I'm newer so I apologize if I fail. 

I tried to make a script to change the icon on my i3 blocks status bar, but I can't make the mute condition work. Any ideas?

Here the script [https://github.com/zeni99ArchLinux/i3-archlinux/blob/Work/config/i3/scripts/audio](url)
```bash

vol=`ponymix get-volume`
muted=`ponymix is-muted`

# determine icon (this part works)
if [ $vol == "0" ]; then
	echo "  $vol"
else
	if [ $vol -le 63 ]; then
		echo "  $vol"
	else
		echo "  $vol"
	fi
fi

# determine mute status (this part doesn't works )
if [ $muted == "0" ]; then
    echo $vol
fi
```

If I write `ponymix is-muted` in my terminal I don't have any output.

**Comment by falconindy** [comment]
is-muted exits 0 (muted) or non-zero (not muted). It has no output. This is how it's documented to work.
